name: HexArch Template CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    env:
      IMAGE_NAME: "hexarch_template"
      TAG: "latest"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build the docker image
        run: |
          docker build . --file Dockerfile --tag ${IMAGE_NAME}:${TAG}
      
      - name: Run the tests
        run: |
          docker run -i ${IMAGE_NAME}:${TAG} bash -c "pytest ./tests --junitxml=results.xml"
      
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: results.xml
      
      - name: Remove Docker image
        run: |
          docker rmi ${IMAGE_NAME}:${TAG}
